name: laihla_lyrics
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.5+23

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.5
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.2.0+1
  flutter_launcher_icons: ^0.10.0
  url_launcher: ^6.1.6
  dio: ^4.0.6
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  animations: ^2.0.7
  get: ^4.6.5
  auto_size_text: ^3.0.0
  google_mobile_ads: ^2.4.0
  flutter_chord_mod: ^0.0.46
  banner_carousel: ^1.2.1
  sliding_sheet: ^0.5.2
  sliding_up_panel: ^2.0.0+1
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  fluttertoast: ^8.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audioplayers: ^5.1.0

  webview_flutter: ^4.4.3
  video_player: ^2.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  flutter_lints: ^2.0.1


flutter_icons:
  android: "launcher_icon"
  ios : true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#373D3B"
  image: assets/logo.png
  android: true
  ios : true

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/chords/
    - assets/khrifahlabu.jpg