name: laihla_lyrics
description: A new Flutter project.

publish_to: 'none'

version: 2.1.1+30

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.0+1
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.1.6
  path_provider: ^2.1.4
  permission_handler: ^12.0.0+1
  dio: ^5.8.0+1       # to fix security warnings
  http: ^1.4.0
  google_mobile_ads: ^6.0.0
  animations: ^2.0.7
  get: ^4.6.5
  auto_size_text: ^3.0.0
  flutter_chord_mod: ^0.0.46
  banner_carousel: ^1.2.1
  sliding_up_panel: ^2.0.0+1
  fluttertoast: ^8.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audioplayers: ^6.1.0
  socket_io_client: ^3.0.0
  image_picker: ^1.1.2
  path: ^1.9.0
  package_info_plus: ^8.3.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  image_path: "assets/logo1.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#506870"
  image: assets/logo.png
  android: true
  ios : true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/chords/
    - assets/bible.json